#!/usr/bin/env bun
/**
 * Sync .env.local with Vercel environment variables.
 *
 * Usage:
 *   bun run env:sync              # pull "development" env vars (default)
 *   bun run env:sync production   # pull production env vars
 *   bun run env:diff              # show keys missing on either side
 */
import { execSync } from "node:child_process"
import { existsSync, readFileSync, renameSync, writeFileSync } from "node:fs"
import { tmpdir } from "node:os"
import { join } from "node:path"

const LOCAL_ONLY_KEYS = [
  "E2E_CLERK_USER_USERNAME",
  "E2E_CLERK_USER_PASSWORD",
  "E2E_CLERK_CREATOR_USERNAME",
  "E2E_CLERK_CREATOR_PASSWORD",
  "E2E_CLERK_ADMIN_USERNAME",
  "E2E_CLERK_ADMIN_PASSWORD",
  "E2E_CREATOR_USERNAME",
]

const ENV_FILE = ".env.local"

function run(cmd: string): string {
  return execSync(cmd, { encoding: "utf8", stdio: ["pipe", "pipe", "inherit"] })
}

function parseEnv(content: string): Map<string, string> {
  const map = new Map<string, string>()
  for (const raw of content.split(/\r?\n/)) {
    const line = raw.trim()
    if (!line || line.startsWith("#")) continue
    const eq = line.indexOf("=")
    if (eq === -1) continue
    const key = line.slice(0, eq).trim()
    let value = line.slice(eq + 1)
    if (value.startsWith('"') && value.endsWith('"')) {
      value = value.slice(1, -1)
    }
    map.set(key, value)
  }
  return map
}

function preserveLocalOnly(): Map<string, string> {
  if (!existsSync(ENV_FILE)) return new Map()
  const current = parseEnv(readFileSync(ENV_FILE, "utf8"))
  const preserved = new Map<string, string>()
  for (const key of LOCAL_ONLY_KEYS) {
    const value = current.get(key)
    if (value !== undefined) preserved.set(key, value)
  }
  return preserved
}

function pullFromVercel(target: string): Map<string, string> {
  const tmp = join(tmpdir(), `vercel-env-${Date.now()}.env`)
  console.log(`→ pulling Vercel "${target}" env vars…`)
  run(`vercel env pull "${tmp}" --environment=${target} --yes`)
  const content = readFileSync(tmp, "utf8")
  return parseEnv(content)
}

function writeMerged(
  fromVercel: Map<string, string>,
  preserved: Map<string, string>,
) {
  const lines: string[] = []
  lines.push("# Generated by scripts/sync-env.ts — do not edit by hand.")
  lines.push("# Source: Vercel dashboard. Run `bun run env:sync` to refresh.")
  lines.push("")
  lines.push("# === From Vercel ===")
  for (const [key, value] of fromVercel) {
    lines.push(`${key}="${value}"`)
  }
  if (preserved.size > 0) {
    lines.push("")
    lines.push("# === Local-only (E2E test creds, etc.) ===")
    for (const [key, value] of preserved) {
      lines.push(`${key}="${value}"`)
    }
  }
  lines.push("")
  const tmp = `${ENV_FILE}.tmp`
  writeFileSync(tmp, lines.join("\n"))
  renameSync(tmp, ENV_FILE)
}

function cmdSync(target: string) {
  const preserved = preserveLocalOnly()
  if (preserved.size > 0) {
    console.log(`→ preserving ${preserved.size} local-only key(s)`)
  }
  const fromVercel = pullFromVercel(target)
  writeMerged(fromVercel, preserved)
  console.log(
    `✓ ${ENV_FILE} updated with ${fromVercel.size} Vercel vars + ${preserved.size} local-only vars`,
  )
}

function cmdDiff() {
  const local = existsSync(ENV_FILE)
    ? parseEnv(readFileSync(ENV_FILE, "utf8"))
    : new Map()
  const vercel = pullFromVercel("development")

  const inVercelMissingLocal: string[] = []
  for (const key of vercel.keys()) {
    if (key.startsWith("VERCEL_")) continue
    if (!local.has(key)) inVercelMissingLocal.push(key)
  }
  const inLocalMissingVercel: string[] = []
  for (const key of local.keys()) {
    if (LOCAL_ONLY_KEYS.includes(key)) continue
    if (!vercel.has(key)) inLocalMissingVercel.push(key)
  }

  console.log("\n— Missing in .env.local (present on Vercel) —")
  console.log(
    inVercelMissingLocal.length ? inVercelMissingLocal.join("\n") : "(none)",
  )
  console.log("\n— Missing on Vercel (present in .env.local) —")
  console.log(
    inLocalMissingVercel.length ? inLocalMissingVercel.join("\n") : "(none)",
  )
  console.log("")
}

const target = process.argv[2] ?? "development"
if (target === "diff") {
  cmdDiff()
} else if (["development", "preview", "production"].includes(target)) {
  cmdSync(target)
} else {
  console.error(`Unknown target: ${target}`)
  console.error("Usage: bun run env:sync [development|preview|production]")
  console.error("       bun run env:diff")
  process.exit(1)
}
